# File generated by Flopy version 3.9.5 on 05/02/2026 at 14:31:45.
BEGIN options
  XT3D_OFF
END options

BEGIN griddata
  alh
    CONSTANT     100.00000000
  ath1
    CONSTANT     100.00000000
END griddata

